--Find total customers by country

    SELECT 
    country,
    COUNT (customer_key) AS customers
    FROM gold.dim_customers
    GROUP BY country
    ORDER BY customers DESC;

            /*
                -- ***Cooler solution with total row***
	                    SELECT 
                        country,
                        customers
                    FROM (
                        SELECT 
                            country,
                            COUNT(customer_key) AS customers,
                            1 AS sort_order
                        FROM gold.dim_customers
                        GROUP BY country

                        UNION ALL

                        SELECT  
                            'Total' AS country,
                            COUNT(customer_key) AS customers,
                            2 AS sort_order
                        FROM gold.dim_customers
                    ) t
                    ORDER BY 
                        sort_order,
                        customers DESC;
            */

--Find total customers by gender
    SELECT 
    gender,
    COUNT (gender) as total_gender
    FROM gold.dim_customers
    GROUP BY gender 
    ORDER BY gender 

--Find total products by category
    SELECT 
    category,
    COUNT (product_key) as total_category

    FROM gold.dim_products
    GROUP BY category 
    ORDER BY total_category DESC

--What is the average costs in each categoty?
    SELECT 
    category,
    AVG(cost) as avg_cost

    FROM gold.dim_products
    GROUP BY category 
    ORDER BY avg_cost DESC

--What is the total revenue generated for each category?

    SELECT 
    p.category,
    SUM (f.sales_amount) AS total_revenue
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
    GROUP BY p.category
    ORDER BY total_revenue DESC

--Find total revenue is generated by each customer
    SELECT
        c.customer_key,
        c.first_name,
        c.last_name,
        SUM (f.sales_amount) AS total_revenue

    FROM gold.fact_sales f
    LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key

    GROUP BY 
        c.customer_key,
        c.first_name,
        c.last_name

    ORDER BY total_revenue DESC


--What is the distribution of sold items across countries?

    SELECT
        c.country,
        SUM (f.quantity) AS total_sold_items

    FROM gold.fact_sales f
    LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key

    GROUP BY 
        c.country
    ORDER BY total_sold_items DESC
